SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS notifications;

SET default_tablespace = '';

CREATE TABLE notifications.notifications (
    id bigint NOT NULL,
    change_status_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    email character varying(255) NOT NULL,
    message character varying(1025) NOT NULL,
    status integer NOT NULL,
    subject character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_code bigint NOT NULL
);

ALTER TABLE notifications.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME notifications.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

SELECT pg_catalog.setval('notifications.notifications_id_seq', 1, false);

ALTER TABLE ONLY notifications.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);